name: Hello Workflow
on: [ push ]
jobs:
  hello-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Hello World using the echo command
        run: echo "Hello, Workflow!"
